spring:
  profiles:
#    remove if needed
    #active: "docker"
  datasource:
    url: jdbc:h2:mem:storeDb
    username: sa
    password: password
  h2:
    console:
      enabled: true
  flyway:
    enabled: false

server:
  port: 8084