version: "3.9"
services:
  database:
    image: postgres:14.0
    ports:
      - "5450:5432"
    environment:
      POSTGRES_PASSWORD: admin
    restart: "unless-stopped"
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql